### ISSUE TITLE
Library does not parse using the Modelica grammar

### ISSUE THREAD

**Issue by sjoelund** [kdavies4/FCSys#2]
I forked the library, trying to fix some minor issues with the parsing, but when doing so I found some bigger problems.
The library uses the structure `{1,2,3}[i]` a lot. But this is not allowed in the Modelica grammar. You have to write code like `index({1,2,3},i)` (with a new index function for each type). Or restructure the code (probably preferred).

**Comment by kdavies4** [comment]
Thanks for your feedback.  It appears that I used that construct 4 times -- twice in the Test subpackage, once in an assertion message, and once in the fixed attribute of an array.  I explicitly expanded the assertion and the fixed attribute.  For now, I've left the Test package as is.

There's a similar construct in the "Conservation of translational momentum" equation of Subregions.Species.Species: (... )[i].  That is more difficult to address because Dymola (version 7.4; I haven't tested others) doesn't support vector multiplication of stream arrays.

For my own education, could you tell me which tool you are using?  I wasn't aware of this issue since it worked in Dymola 7.4.  It doesn't seem that the Modelica spec indicates one way or another (or could you show me exactly where?), so I figured that {1,2,3}[i](or at least %28{1,2,3}%29[i]) is just like indexing a variable.  Maybe there's a different interpretation among the tools.

Thanks again.

**Comment by sjoelund** [comment]
I am an OpenModelica developer, so I of course used OpenModelica. I also used https://svn.modelica.org/projects/Modelica/branches/tools/MoParser/, which is the MapleSim stand-alone parser.

In the specification it is section B 2.7: The only way to use `[` ... `]` in an expression is as array subscripts on a component reference (`a[1].b[2]`) or as a matrix (`[1,2,3 ; 4,5,6]`).

**Comment by kdavies4** [comment]
Thanks.  I may try MoParser, but probably not yet.  I see section 10.5 Array Indexing, but I don't see section 2.7 or appendix B in the Modelica Language Specification version 3.1 or 3.3.  I also searched for the text, but I couldn't find it.

I did find the following, which seems to be another valid usage of `[` ... `]`:  
    Real[3,0] A, B;

I'm not trying to be difficult, and I agree that some or even all of my usage of that construct is not ideal.  However, it seemed like the best way to get the job done considering other limitations (of Modelica and the time I have).

**Comment by sjoelund** [comment]
I don't disagree it is not a good way to solve things or I would have made a nice-looking patch that does the same thing ;) And yes, you can use `[` for declaring array dimensions, but these are not used in expressions.
B.2.7 is page 249 in Spec 3.3 or in the documentation string of ModelicaReference.ModelicaGrammar.

**Comment by kdavies4** [comment]
Ok, thanks for the detail.  That parser syntax is a bit over my head at this point, but I trust your interpretation.  I'll see what I can do with this, but it may be some time (even 2 or 3 months) before I can get it completely resolved.

**Comment by kdavies4** [comment]
I went ahead and fixed the rest of the issues.  It now passes the moparser check.  Thanks for your help.
